-- generated by rvpm hook converter; do not edit by hand

-- dpp inlineVimrcs: lua/vimrc/*, nvim|vim/*, unix|windows/*
do
  local root = vim.fs.joinpath(vim.env.NVIM_CONFIG_HOME, 'lua', 'vimrc')
  local dirs = {
    '',
    vim.fn.has('nvim') == 1 and 'nvim' or 'vim',
    vim.fn.has('win32') == 1 and 'windows' or 'unix',
  }
  for _, dir in ipairs(dirs) do
    local path = dir == '' and root or vim.fs.joinpath(root, dir)
    local names = {}
    local ok, iter = pcall(vim.fs.dir, path)
    if ok then
      for name, typ in iter do
        if typ == 'file' and name:sub(-4) == '.lua' then
          names[#names + 1] = name
        end
      end
    end
    table.sort(names)
    local prefix = dir == '' and 'vimrc.' or ('vimrc.' .. dir .. '.')
    for _, name in ipairs(names) do
      require(prefix .. name:sub(1, -5))
    end
  end
end

vim.api.nvim_create_autocmd('FileType', {
  pattern = '*',
  callback = function()
    -- Disable automatically insert comment
    vim.opt_local.formatoptions:remove({ 't', 'c', 'r', 'o' })
    vim.opt_local.formatoptions:append({ 'm', 'M', 'B', 'l' })
    -- disable conceal
    vim.opt_local.conceallevel = 0
    -- Disable autowrap
    if vim.bo.textwidth ~= 70 and vim.bo.filetype ~= 'help' then
      vim.bo.textwidth = 0
    end
    if not vim.bo.modifiable then
      vim.opt_local.foldenable = false
      vim.opt_local.foldcolumn = '0'
      vim.opt_local.colorcolumn = ''
    end
  end,
})

vim.api.nvim_create_autocmd('FileType', {
  pattern = 'go',
  callback = function()
    vim.api.nvim_set_hl(0, 'goErr', { link = 'WarningMsg', default = true })
    vim.fn.matchadd('goErr', [[\<err\>]])
  end,
})

vim.api.nvim_create_autocmd('FileType', {
  pattern = 'help',
  callback = function()
    -- Add { and } to iskeyword
    vim.opt_local.iskeyword:append({ '^{', '^}' })

    -- Link help highlight groups to Special
    vim.api.nvim_set_hl(0, 'helpBar', { link = 'Special', default = true })
    vim.api.nvim_set_hl(0, 'helpBacktick', { link = 'Special', default = true })
    vim.api.nvim_set_hl(0, 'helpStar', { link = 'Special', default = true })
    vim.api.nvim_set_hl(0, 'helpIgnore', { link = 'Special', default = true })

    -- Right-align the last [*|]...[*|] tag on a line
    local function right_align(linenr)
      local line = vim.fn.getline(linenr)
      local m = vim.fn.matchlist(line, [[^\%(\S\+ \?\)\+\?\s\+\([*|].\+[*|]\)]])
      if #m == 0 then
        return
      end
      -- m[2] = text part, m[3] = tag part (matchlist is 1-indexed in Lua)
      local spaces = string.rep(' ', vim.bo.textwidth - #m[2] - #m[3])
      vim.fn.setline(linenr, m[2] .. spaces .. m[3])
    end

    local function right_aligns(start, end_)
      for linenr = start, end_ do
        right_align(linenr)
      end
    end

    -- :RightAlign command (range)
    vim.api.nvim_buf_create_user_command(0, 'RightAlign', function(opts)
      right_aligns(opts.line1, opts.line2)
    end, { range = true, desc = 'Right-align help tags' })

    -- Mappings
    vim.keymap.set(
      'n',
      'mm',
      '<Cmd>RightAlign<CR>',
      { buffer = true, desc = 'Right-align help tags' }
    )
    vim.keymap.set(
      'x',
      'mm',
      ':RightAlign<CR>',
      { buffer = true, silent = true, desc = 'Right-align help tags (visual)' }
    )
  end,
})

vim.api.nvim_create_autocmd('FileType', {
  pattern = 'lua',
  callback = function()
    vim.opt_local.foldmethod = 'indent'
    vim.bo.shiftwidth = 2
    vim.bo.softtabstop = 2
    vim.bo.expandtab = true
    vim.bo.tabstop = 2
  end,
})

vim.api.nvim_create_autocmd('FileType', {
  pattern = 'python',
  callback = function()
    vim.opt_local.foldmethod = 'indent'
    vim.bo.softtabstop = 4
    vim.bo.shiftwidth = 4
    vim.bo.tabstop = 4
    vim.bo.textwidth = 80
    vim.opt.smarttab = true
    vim.bo.expandtab = true
    vim.bo.smartindent = false
  end,
})

vim.api.nvim_create_autocmd('FileType', {
  pattern = 'qf',
  callback = function()
    vim.opt_local.wrap = true
  end,
})

vim.api.nvim_create_autocmd('FileType', {
  pattern = 'qfreplace',
  callback = function()
    vim.opt_local.foldenable = false
  end,
})

vim.api.nvim_create_autocmd('FileType', {
  pattern = 'typescript',
  callback = function()
    -- TODO: https://vim-jp.org/vim-users-jp/2009/10/08/Hack-84.html
    vim.opt_local.foldmethod = 'syntax'
    vim.bo.shiftwidth = 2
    -- disable indent
    vim.bo.indentexpr = ''
  end,
})

vim.api.nvim_create_autocmd('FileType', {
  pattern = 'toml',
  callback = function()
    -- Fold blank / indented lines
    _G.__toml_fold = function(lnum)
      local line = vim.fn.getline(lnum)
      if line == '' or line:match('^%s+') then
        return '1'
      end
      return '0'
    end
    vim.opt_local.foldenable = true
    vim.opt_local.foldmethod = 'expr'
    vim.opt_local.foldexpr = 'v:lua.__toml_fold(v:lnum)'
  end,
})

vim.api.nvim_create_autocmd('FileType', {
  pattern = 'vim',
  callback = function()
    vim.bo.softtabstop = 2
    vim.bo.shiftwidth = 2
    vim.bo.tabstop = 2
    vim.bo.textwidth = 78
  end,
})

vim.api.nvim_create_autocmd('FileType', {
  pattern = 'yaml',
  callback = function()
    vim.opt_local.iskeyword:append({ '-' })
    -- Don't adjust indent by "#"
    vim.opt_local.indentkeys:remove({ '0#' })
  end,
})
