# Faster coding with features such as snippets, autocompletion, and more.

# ===========================================================================
# Input engines / Japanese
# ===========================================================================
# Search engine of Japanese (by Roma-ji)
[[plugins]]
repo = "lambdalisue/kensaku.vim"
denops_wait = false

# Japanese input engine
[[plugins]]
repo = "vim-skk/skkeleton"
denops_wait = false
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/skkeleton.dpp"

[[plugins]]
repo = "NI57721/skkeleton-state-popup"
on_source = "skkeleton"

[[plugins]]
repo = "NI57721/skkeleton-henkan-highlight"
on_source = "skkeleton"
hook_source = '''
  highlight SkkeletonHenkan
  \ gui=underline term=underline cterm=underline
  highlight SkkeletonHenkanSelect
  \ gui=underline,reverse term=underline,reverse cterm=underline,reverse
'''

# ===========================================================================
# Better coding
# ===========================================================================
# lexima.vim: Auto pair
[[plugins]]
repo = "cohama/lexima.vim"
on_event = ["BufReadPost", "BufNewFile"]
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/lexima.vim.dpp"

# vim-findent: find good indent size automatically
[[plugins]]
repo = "lambdalisue/vim-findent"

# vim-sandwich: add/delete/replace surroundings
[[plugins]]
repo = "machakann/vim-sandwich"
on_map = { n = ["<Plug>"], o = "<Plug>", x = "<Plug>" }
# on_map = { n = ["<Plug>", "s"], o = "<Plug>", x = "<Plug>" }
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/vim-sandwich.dpp"

# vim-niceblock: Enable to call `I` and `A` for All visual mode
[[plugins]]
repo = "kana/vim-niceblock"
on_map = { x = "<Plug>" }
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/vim-niceblock.dpp"

# dial.nvim - extended increment/decrement
[[plugins]]
repo = "monaqa/dial.nvim"
on_map = { n = ["<C-a>", "<C-x>"], x = ["<C-a>", "<C-x>"] }

