# Test some colorschemes; If my color theme is concreted,
# remove other colorschemes

[[plugins]]
repo = "folke/tokyonight.nvim"
lazy = false
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/tokyonight.nvim.dpp"

[[plugins]]
repo = "EdenEast/nightfox.nvim"
lazy = false
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/nightfox.nvim.dpp"

[[plugins]]
repo = "catppuccin/nvim"
name = "catppuccin"
lazy = false
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/catppuccin.nvim.dpp"

[[plugins]]
repo = "rebelot/kanagawa.nvim"
lazy = false

