# ddc.vim and related files

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = 'denops.vim'
#on_source = 'ddt.vim'
on_event = ['InsertEnter', 'CmdlineEnter']
hooks_file = '$NVIM_CONFIG_HOME/lua/hooks/ddc.lua'

[[plugins]]
repo = 'Shougo/pum.vim'
hooks_file = '$NVIM_CONFIG_HOME/lua/hooks/pum.lua'

# ---------------------------------------------------------------------------
# UI
# ---------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = 'pum.vim'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-ui-none'
group = 'ddc'

# Other UI
#repo = 'Shougo/ddc-ui-native'
#repo = 'Shougo/ddc-ui-inline'

# ---------------------------------------------------------------------------
# SOURCE
# ---------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/ddc-source-around'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-source-shell_native'
group = 'ddc'

# Tell me the diff of `shell_native` and `shell`
[[plugins]]
repo = 'Shougo/ddc-source-shell'
group = 'ddc'

[[plugins]]
repo = 'Shougo/ddc-source-shell_history'
group = 'ddc'

# ---------------------------------------------------------------------------
# FILTER
# ---------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'
group = 'ddc'

# ---------------------------------------------------------------------------
# SORTER
# ---------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
group = 'ddc'

# ---------------------------------------------------------------------------
# CONVERTER
# ---------------------------------------------------------------------------

#[[plugins]]
#repo = 'Shougo/dpp-ext-lazy'
#rtp = ''
#
#[[plugins]]
#repo = 'Shougo/dpp-ext-toml'
#hook_add = '''
#" Enable dpp toml syntax.
#if !has('nvim')
#  autocmd MyAutoCmd CursorHold */rc/*.toml call dpp#ext#toml#syntax()
#endif
#'''

# DDC AND SKKELETON (Japanese input)
#[[multiple_hooks]]
#plugins = ['ddc.vim', 'skkeleton']
#hooks_file = '$BASE_DIR/ddc_skkeleton.vim'

