# Denops itself and Denops-related plugins
[[plugins]]
repo = "vim-denops/denops.vim"
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/denops.vim.lua"

[[plugins]]
repo = "lambdalisue/kensaku.vim"
denops_wait = false

[[plugins]]
repo = "vim-skk/skkeleton"
on_map = { ict = "<Plug>(skkeleton-" }
denops_wait = false
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/skkeleton.lua"

[[plugins]]
repo = "NI57721/skkeleton-state-popup"
on_source = "skkeleton"

[[plugins]]
repo = "NI57721/skkeleton-henkan-highlight"
on_source = "skkeleton"
hook_source = '''
  highlight SkkeletonHenkan
  \ gui=underline term=underline cterm=underline
  highlight SkkeletonHenkanSelect
  \ gui=underline,reverse term=underline,reverse cterm=underline,reverse
'''
