# Denops-related plugins
# NVIM inside NVIM
[[plugins]]
repo = "lambdalisue/vim-guise"
depends = "denops.vim"
# loaded when `ddt.vim` or `gin` is sourced.
on_source = ["ddt.vim", "gin"]
# or if this is "child" nvim process, load on events [`VimEnter`, ... etc ];
# then child nvim process is moved to new tab of the parent nvim
on_event = ["VimEnter"]
# see `:h dpp_plugin_option_on_if`
# TODO: Not use `$NVIM` directly now, but set variable to show `is_parent`
# and check `(is_parent flag exists) and (not is_parent)` to source in the future.
on_if = "exists('$NVIM')"

