# DO LIKE https://www.lazyvim.org/plugins/editor, but some plugins are
# delegated to `denops`; see other `deps` toml files.

# ===========================================================================
# Git
# ===========================================================================
[[plugins]]
repo = "lambdalisue/vim-gin"
depends = "denops.vim"
on_event = ["DenopsReady"]
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/vim-gin.dpp"

# gitsigns.nvim - Git integration for buffers
[[plugins]]
repo = "lewis6991/gitsigns.nvim"
on_event = ["BufReadPost", "BufNewFile"]
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/gitsigns.nvim.dpp"

# ---------------------------------------------------------------------------
# Integrations with some softwares
# ---------------------------------------------------------------------------

# TODO: merge it with other plugins via `multiple hooks`
# TODO: think that we can use `ddu` with this plugin;
#       or create new `ddu-ui` and `ddu-source` to show keymaps
# which-key.nvim - keybinding hints
[[plugins]]
repo = "folke/which-key.nvim"
on_event = "UIEnter"
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/which-key.nvim.dpp"

# ---------------------------------------------------------------------------
# Task runner
# ---------------------------------------------------------------------------
# overseer.nvim - task runner and job management
[[plugins]]
repo = "stevearc/overseer.nvim"
on_event = "VimEnter"
# on_map = { n = ["[RUNNER]"] }
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/overseer.nvim.dpp"

# NVIM inside NVIM
[[plugins]]
repo = "lambdalisue/vim-guise"
depends = "denops.vim"
# loaded when `ddt.vim` or `gin` is sourced.
on_source = ["ddt.vim", "gin"]
# or if this is "child" nvim process, load on events [`VimEnter`, ... etc ];
# then child nvim process is moved to new tab of the parent nvim
on_event = ["VimEnter"]
# see `:h dpp_plugin_option_on_if`
# TODO: Not use `$NVIM` directly now, but set variable to show `is_parent`
# and check `(is_parent flag exists) and (not is_parent)` to source in the future.
on_if = "exists('$NVIM')"

