# ---------------------------------------------------------------------------
# Previm: Preview the markdown file
# ---------------------------------------------------------------------------
[[plugins]]
repo = "previm/previm"
on_ft = ["markdown", "rst"]
# TODO: Custom `xdg-open` (we can't call xdg-open in the container)
hook_source = '''
  let g:previm_open_cmd = 'TODO'
'''

# ---------------------------------------------------------------------------
# Help linter
# ---------------------------------------------------------------------------
[[plugins]]
repo = "machakann/vim-vimhelplint"
on_ft = "help"

[plugins.ftplugin]
help = '''
 nnoremap <buffer> ,r  <Cmd>VimhelpLint!<CR>
'''

