# Lazy-loaded plugins.

# ---------------------------------------------------------------------------
# cmdline.vim — render the command line in a floating window
# ---------------------------------------------------------------------------
[[plugins]]
repo = "Shougo/cmdline.vim"
on_source = ["ddu.vim"]
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/cmdline.vim.dpp"

# ---------------------------------------------------------------------------
# Quickfix plugins
# ---------------------------------------------------------------------------
#
[[plugins]]
repo = "thinca/vim-qfreplace"
on_ft = ["qf"]

[plugins.ftplugin]
qf = '''
  nnoremap <buffer> r <Cmd>Qfreplace<CR>
'''

[[plugins]]
repo = "itchyny/vim-qfedit"
# on_event = ["BufReadPost", "BufNewFile"]
on_ft = ["qf"]

