# Lazy-loaded plugins.

# ---------------------------------------------------------------------------
# cmdline.vim — render the command line in a floating window
# ---------------------------------------------------------------------------
[[plugins]]
repo = "Shougo/cmdline.vim"
on_source = ["ddu.vim"]
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/cmdline.vim.lua"

# ---------------------------------------------------------------------------
# Previm: Preview the markdown file
# ---------------------------------------------------------------------------
[[plugins]]
repo = "previm/previm"
on_ft = ["markdown", "rst"]
# TODO: Custom `xdg-open` (we can't call xdg-open in the container)
hook_source = '''
  let g:previm_open_cmd = 'TODO'
'''

# ---------------------------------------------------------------------------
# vim-findent: find good indent size automatically
# ---------------------------------------------------------------------------
[[plugins]]
repo = "lambdalisue/vim-findent"

# ---------------------------------------------------------------------------
# vim-niceblock: Enable to call `I` and `A` for All visual mode
# ---------------------------------------------------------------------------
[[plugins]]
repo = "kana/vim-niceblock"
on_map = { x = "<Plug>" }
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/vim-niceblock.lua"

# ---------------------------------------------------------------------------
# vim-sandwich: add/delete/replace surroundings
# ---------------------------------------------------------------------------
[[plugins]]
repo = "machakann/vim-sandwich"
on_map = { n = ["<Plug>"], o = "<Plug>", x = "<Plug>" }
# on_map = { n = ["<Plug>", "s"], o = "<Plug>", x = "<Plug>" }
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/vim-sandwich.lua"

# ---------------------------------------------------------------------------
# Quickfix plugins
# ---------------------------------------------------------------------------
#
[[plugins]]
repo = "thinca/vim-qfreplace"
on_ft = ["qf"]

[plugins.ftplugin]
qf = '''
  nnoremap <buffer> r <Cmd>Qfreplace<CR>
'''

[[plugins]]
repo = "itchyny/vim-qfedit"
# on_event = ["BufReadPost", "BufNewFile"]
on_ft = ["qf"]

# ---------------------------------------------------------------------------
# Help linter
# ---------------------------------------------------------------------------
[[plugins]]
repo = "machakann/vim-vimhelplint"
on_ft = "help"

[plugins.ftplugin]
help = '''
 nnoremap <buffer> ,r  <Cmd>VimhelpLint!<CR>
'''

# TODO: add `folke/which-key.nvim` add add as a ddu source

# TODO: Set config of these plugins (below)
[[plugins]]
repo = "stevearc/aerial.nvim"
on_event = ["BufReadPost", "BufNewFile"]

