# Make each file type rule; like indent etc.
hook_files = ["$NVIM_CONFIG_HOME/lua/hooks/ft.lua"]

[[plugins]]
repo = "vim-jp/vimdoc-ja"
extAttrs = { installerMinCommitDays = 0 }

[[plugins]]
repo = "kana/vim-operator-user"
