[[plugins]]
repo = 'romus204/tree-sitter-manager.nvim'
if = '!has("win32")'
on_event = ['VimEnter', 'BufRead', 'CursorHold']
on_ft = ['help']
external_commands = ['tree-sitter']
lua_source = '''
  -- Install parsers
  require("tree-sitter-manager").setup({
    ensure_installed = {
      'lua',
      'rust',
      'python',
      'toml',
      'typescript',
      'vim',
      'vimdoc',
    },
  })
'''
