# Tree-sitter
[[plugins]]
repo = 'romus204/tree-sitter-manager.nvim'
if = '!has("win32")'
on_event = ['VimEnter', 'BufRead', 'CursorHold']
on_ft = ['help']
external_commands = ['tree-sitter']
lua_source = '''
  -- Install parsers
  require("tree-sitter-manager").setup({
    ensure_installed = {
      'lua',
      'rust',
      'python',
      'toml',
      'typescript',
      'vim',
      'vimdoc',
    },
  })
'''

# LSP

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hooks_file = '$NVIM_CONFIG_HOME/lua/hooks/nvim-lspconfig.lua'

[[plugins]]
repo = 'williamboman/mason.nvim'
depends = ['nvim-lspconfig', 'ddc-source-lsp']
on_event = 'FileType'
hooks_file = '$NVIM_CONFIG_HOME/lua/hooks/mason.lua'

# Bridge LSP servers; Merge with Tree-sitter and combine multiple LSP
[[plugins]]
repo = 'atusy/kakehashi.nvim'
on_source = 'mason.nvim'
external_commands = ['kakehashi']
hooks_file = '$NVIM_CONFIG_HOME/lua/hooks/kakehashi.lua'

