# loaded ONLY PLUGINS IN THIS FILES (and few `lazy = false` plugins) eager

# Make each file type rule; like indent etc.
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/ft.dpp"

# ===========================================================================
# Dpp and it's plugins (`dpp-ext`)
# ===========================================================================

[[plugins]]
repo = "Shougo/dpp.vim"
description = "Dark powered plugin manager for Vim/Neovim"
rtp = ""

[[plugins]]
repo = "Shougo/dpp-ext-lazy"
rtp = ""

[[plugins]]
repo = "Shougo/dpp-ext-toml"
group = "dpp"
hook_add = '''
" Enable dpp toml syntax.
if !has('nvim')
  autocmd vimrc CursorHold */deps/*.toml call dpp#ext#toml#syntax()
endif
'''

[[plugins]]
repo = "Shougo/dpp-ext-local"
group = "dpp"

[[plugins]]
repo = "Shougo/dpp-ext-installer"
group = "dpp"

[[plugins]]
repo = "Shougo/dpp-ext-packspec"
group = "dpp"

[[plugins]]
repo = "Shougo/dpp-protocol-git"
group = "dpp"

[[plugins]]
repo = "Shougo/dpp-protocol-http"
group = "dpp"

# ===========================================================================
# VIMDOC
# ===========================================================================
[[plugins]]
repo = "vim-jp/vimdoc-ja"
extAttrs = { installerMinCommitDays = 0 }

