# TODO: Do below.
# folke/todo-comments.nvim
# ===========================================================================
# Notification and output
# ===========================================================================

# Notify (basic); float popup window
[[plugins]]
repo = "rcarriga/nvim-notify"
lazy = false
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/nvim-notify.dpp"

# Notify (external)
# TODO: It may conflict with `Dark-powered UI`;
#       So we need to check it.
# [[plugins]]
# repo = "folke/noice.nvim"
# depends = ["nvim-notify", "nui.nvim"]
# on_event = ["UIEnter"]
# [[plugins]]
# repo = "MunifTanjim/nui.nvim"
# on_event = ["UIEnter"]

# Notifications
[[plugins]]
repo = "j-hui/fidget.nvim"
lazy = false
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/fidget.nvim.dpp"

# ===========================================================================
# side line
# ===========================================================================
# aerial.nvim - code outline / symbols
# TODO: Add config
[[plugins]]
repo = "stevearc/aerial.nvim"
on_event = ["BufReadPost", "BufNewFile"]
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/aerial.nvim.dpp"

# ===========================================================================
# Statusline / WinBar
# ===========================================================================
# heirline.nvim - statusline (and its deps)
[[plugins]]
repo = "rebelot/heirline.nvim"
on_event = ["UIEnter"]
# All colorscheme should be read before heirline.
depends = ["catppuccin", "nvim-web-devicons"]
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/heirline.nvim.dpp"

[[plugins]]
repo = "nvim-tree/nvim-web-devicons"

