-- generated by rvpm hook converter; do not edit by hand
-- inline from deps (hook_source); P5: single vim.cmd block for multiline highlight
vim.cmd([[
highlight SkkeletonHenkan gui=underline term=underline cterm=underline
highlight SkkeletonHenkanSelect gui=underline,reverse term=underline,reverse cterm=underline,reverse
]])
