-- AUTO-GENERATED by scripts/gen_deps.ts — do not edit by hand.
-- Source: deps/{dpp,denops,neovim,merge}.toml
-- Regenerate: `deno task gen`

local M = {}

M.minimum_deps = {
  'Shougo/dpp.vim',
  'Shougo/dpp-ext-lazy',
}

M.normal_deps = {
  'Shougo/dpp-ext-toml',
  'Shougo/dpp-ext-local',
  'Shougo/dpp-ext-installer',
  'Shougo/dpp-ext-packspec',
  'Shougo/dpp-protocol-git',
  'Shougo/dpp-protocol-http',
  'vim-denops/denops.vim',
}

return M
