-- generated by rvpm hook converter; do not edit by hand
vim.keymap.set(
  'x',
  'I',
  '<Plug>(niceblock-I)',
  { noremap = true, desc = 'Insert at blockwise visual selection' }
)

vim.keymap.set(
  'x',
  'A',
  '<Plug>(niceblock-A)',
  { noremap = true, desc = 'Append at blockwise visual selection' }
)
