-- generated by rvpm hook converter; do not edit by hand
-- kakehashi.nvim (upstream) entry point.
--
-- The Neovim client config lives in after/lsp/kakehashi.lua (loaded lazily
-- by `vim.lsp.config['kakehashi']`, following atusy's dotfiles layout).
-- This hook only enables the config: `vim.lsp.enable` eagerly resolves it,
-- which triggers the after/lsp load — and must not be called from inside
-- that file (it would recurse).
--
-- kakehashi is the sole Neovim LSP client; bridged servers (denols,
-- emmylua_ls, gopls, pyright, tombi, vtsls) run as its children
-- (rust_analyzer is NOT bridged — rustaceanvim owns the rust client;
-- see deps/testing.toml). Server binaries are installed by mise,
-- NOT mason.nvim.

vim.lsp.enable('kakehashi')
