-- generated by rvpm hook converter; do not edit by hand
-- Plugin functions cannot be called here (the plugin is not sourced yet).
-- Only mappings and global options.
vim.keymap.set(
  { 'i', 'c', 't' },
  '<C-j>',
  '<Cmd>call skkeleton#handle("toggle", {})<CR>',
  { desc = 'skkeleton: toggle' }
)
vim.keymap.set(
  'n',
  '<C-j>',
  'i<Cmd>call skkeleton#handle("enable", {})<CR>',
  { desc = 'skkeleton: enable' }
)
