-- generated by rvpm hook converter; do not edit by hand
-- nvim-dap-virtual-text setup with defaults (LazyVim: opts = {}).
-- nvim-dap is already sourced here (`depends` in deps/testing.toml).
require('nvim-dap-virtual-text').setup({})
