-- generated by rvpm hook converter; do not edit by hand
vim.fn['ddu#custom#load_config'](
  vim.fn.expand(vim.fs.joinpath(vim.env.NVIM_CONFIG_HOME, 'denops', 'ddu.ts'))
)

-- shared multiple_hooks
require('hooks.shared.ddu_gin').setup()
