/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 19
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 13
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_start_marker_line = 1,
  sym_end_marker_line = 2,
  aux_sym_line_token1 = 3,
  anon_sym_LF = 4,
  sym_wrapper_start_line = 5,
  sym_wrapper_end_line = 6,
  sym_document = 7,
  sym_hook_block = 8,
  sym_line = 9,
  sym_hook_line = 10,
  aux_sym_document_repeat1 = 11,
  aux_sym_hook_block_repeat1 = 12,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_start_marker_line] = "start_marker_line",
  [sym_end_marker_line] = "end_marker_line",
  [aux_sym_line_token1] = "line_token1",
  [anon_sym_LF] = "\n",
  [sym_wrapper_start_line] = "wrapper_start_line",
  [sym_wrapper_end_line] = "wrapper_end_line",
  [sym_document] = "document",
  [sym_hook_block] = "hook_block",
  [sym_line] = "line",
  [sym_hook_line] = "hook_line",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_hook_block_repeat1] = "hook_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_start_marker_line] = sym_start_marker_line,
  [sym_end_marker_line] = sym_end_marker_line,
  [aux_sym_line_token1] = aux_sym_line_token1,
  [anon_sym_LF] = anon_sym_LF,
  [sym_wrapper_start_line] = sym_wrapper_start_line,
  [sym_wrapper_end_line] = sym_wrapper_end_line,
  [sym_document] = sym_document,
  [sym_hook_block] = sym_hook_block,
  [sym_line] = sym_line,
  [sym_hook_line] = sym_hook_line,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_hook_block_repeat1] = aux_sym_hook_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_start_marker_line] = {
    .visible = true,
    .named = true,
  },
  [sym_end_marker_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_wrapper_start_line] = {
    .visible = true,
    .named = true,
  },
  [sym_wrapper_end_line] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_hook_block] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_hook_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_hook_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 2,
  [8] = 4,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 9,
  [14] = 10,
  [15] = 11,
  [16] = 16,
  [17] = 17,
  [18] = 16,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (eof) ADVANCE(2);
      if (lookahead == '-') ADVANCE(11);
      if (lookahead == 'E') ADVANCE(15);
      if (lookahead == 'l') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(28);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_start_marker_line);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_end_marker_line);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '\n') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '-') ADVANCE(11);
      if (lookahead == 'E') ADVANCE(15);
      if (lookahead == 'l') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '<') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '<') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == 'F') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == 'O') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == 'a') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == 'u') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '{') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '}') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '}') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_wrapper_start_line);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_wrapper_end_line);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_start_marker_line] = ACTIONS(1),
    [sym_end_marker_line] = ACTIONS(1),
    [aux_sym_line_token1] = ACTIONS(1),
    [sym_wrapper_start_line] = ACTIONS(1),
    [sym_wrapper_end_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(17),
    [sym_hook_block] = STATE(3),
    [sym_line] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_start_marker_line] = ACTIONS(5),
    [sym_end_marker_line] = ACTIONS(7),
    [aux_sym_line_token1] = ACTIONS(9),
    [sym_wrapper_start_line] = ACTIONS(7),
    [sym_wrapper_end_line] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_hook_block] = STATE(4),
    [sym_line] = STATE(12),
    [sym_hook_line] = STATE(4),
    [aux_sym_hook_block_repeat1] = STATE(4),
    [sym_start_marker_line] = ACTIONS(11),
    [sym_end_marker_line] = ACTIONS(13),
    [aux_sym_line_token1] = ACTIONS(15),
    [sym_wrapper_start_line] = ACTIONS(17),
    [sym_wrapper_end_line] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym_hook_block] = STATE(5),
    [sym_line] = STATE(5),
    [aux_sym_document_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_start_marker_line] = ACTIONS(5),
    [sym_end_marker_line] = ACTIONS(21),
    [aux_sym_line_token1] = ACTIONS(9),
    [sym_wrapper_start_line] = ACTIONS(21),
    [sym_wrapper_end_line] = ACTIONS(21),
  },
  [STATE(4)] = {
    [sym_hook_block] = STATE(6),
    [sym_line] = STATE(12),
    [sym_hook_line] = STATE(6),
    [aux_sym_hook_block_repeat1] = STATE(6),
    [sym_start_marker_line] = ACTIONS(11),
    [sym_end_marker_line] = ACTIONS(23),
    [aux_sym_line_token1] = ACTIONS(15),
    [sym_wrapper_start_line] = ACTIONS(17),
    [sym_wrapper_end_line] = ACTIONS(17),
  },
  [STATE(5)] = {
    [sym_hook_block] = STATE(5),
    [sym_line] = STATE(5),
    [aux_sym_document_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_start_marker_line] = ACTIONS(27),
    [sym_end_marker_line] = ACTIONS(30),
    [aux_sym_line_token1] = ACTIONS(33),
    [sym_wrapper_start_line] = ACTIONS(30),
    [sym_wrapper_end_line] = ACTIONS(30),
  },
  [STATE(6)] = {
    [sym_hook_block] = STATE(6),
    [sym_line] = STATE(12),
    [sym_hook_line] = STATE(6),
    [aux_sym_hook_block_repeat1] = STATE(6),
    [sym_start_marker_line] = ACTIONS(36),
    [sym_end_marker_line] = ACTIONS(39),
    [aux_sym_line_token1] = ACTIONS(41),
    [sym_wrapper_start_line] = ACTIONS(44),
    [sym_wrapper_end_line] = ACTIONS(44),
  },
  [STATE(7)] = {
    [sym_hook_block] = STATE(8),
    [sym_line] = STATE(12),
    [sym_hook_line] = STATE(8),
    [aux_sym_hook_block_repeat1] = STATE(8),
    [sym_start_marker_line] = ACTIONS(11),
    [sym_end_marker_line] = ACTIONS(47),
    [aux_sym_line_token1] = ACTIONS(15),
    [sym_wrapper_start_line] = ACTIONS(17),
    [sym_wrapper_end_line] = ACTIONS(17),
  },
  [STATE(8)] = {
    [sym_hook_block] = STATE(6),
    [sym_line] = STATE(12),
    [sym_hook_line] = STATE(6),
    [aux_sym_hook_block_repeat1] = STATE(6),
    [sym_start_marker_line] = ACTIONS(11),
    [sym_end_marker_line] = ACTIONS(49),
    [aux_sym_line_token1] = ACTIONS(15),
    [sym_wrapper_start_line] = ACTIONS(17),
    [sym_wrapper_end_line] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(53), 1,
      aux_sym_line_token1,
    ACTIONS(51), 5,
      ts_builtin_sym_end,
      sym_start_marker_line,
      sym_end_marker_line,
      sym_wrapper_start_line,
      sym_wrapper_end_line,
  [11] = 2,
    ACTIONS(57), 1,
      aux_sym_line_token1,
    ACTIONS(55), 5,
      ts_builtin_sym_end,
      sym_start_marker_line,
      sym_end_marker_line,
      sym_wrapper_start_line,
      sym_wrapper_end_line,
  [22] = 2,
    ACTIONS(61), 1,
      aux_sym_line_token1,
    ACTIONS(59), 5,
      ts_builtin_sym_end,
      sym_start_marker_line,
      sym_end_marker_line,
      sym_wrapper_start_line,
      sym_wrapper_end_line,
  [33] = 2,
    ACTIONS(65), 1,
      aux_sym_line_token1,
    ACTIONS(63), 4,
      sym_start_marker_line,
      sym_end_marker_line,
      sym_wrapper_start_line,
      sym_wrapper_end_line,
  [43] = 2,
    ACTIONS(53), 1,
      aux_sym_line_token1,
    ACTIONS(51), 4,
      sym_start_marker_line,
      sym_end_marker_line,
      sym_wrapper_start_line,
      sym_wrapper_end_line,
  [53] = 2,
    ACTIONS(57), 1,
      aux_sym_line_token1,
    ACTIONS(55), 4,
      sym_start_marker_line,
      sym_end_marker_line,
      sym_wrapper_start_line,
      sym_wrapper_end_line,
  [63] = 2,
    ACTIONS(61), 1,
      aux_sym_line_token1,
    ACTIONS(59), 4,
      sym_start_marker_line,
      sym_end_marker_line,
      sym_wrapper_start_line,
      sym_wrapper_end_line,
  [73] = 1,
    ACTIONS(67), 1,
      anon_sym_LF,
  [77] = 1,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
  [81] = 1,
    ACTIONS(71), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 11,
  [SMALL_STATE(11)] = 22,
  [SMALL_STATE(12)] = 33,
  [SMALL_STATE(13)] = 43,
  [SMALL_STATE(14)] = 53,
  [SMALL_STATE(15)] = 63,
  [SMALL_STATE(16)] = 73,
  [SMALL_STATE(17)] = 77,
  [SMALL_STATE(18)] = 81,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hook_block_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hook_block_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_hook_block_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hook_block_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hook_block, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hook_block, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hook_block, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hook_block, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hook_line, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hook_line, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [69] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dpp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dpp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
