-- generated by rvpm hook converter; do not edit by hand
-- P5: defer until overseer loads (nvim-dap promoted eager; overseer stays lazy on VimEnter)
vim.api.nvim_create_autocmd('User', {
  pattern = 'rvpm_loaded_overseer.nvim',
  once = true,
  callback = function()
    require('overseer').enable_dap()
  end,
})
