-- generated by rvpm hook converter; do not edit by hand
-- nvim-dap keymaps following LazyVim's keymap layout
-- (https://www.lazyvim.org/keymaps#nvim-dap), adapted to the `[DAP]` prefix:
-- `<Leader>D` = `[DAP]` (mappings.lua), so `<Leader>Dc` == LazyVim `<leader>dc`.
-- `require('dap')` is called lazily inside callbacks; nvim-dap is sourced
-- after overseer (on_post_source in deps/testing.toml).
-- Keymaps are sorted alphabetically (case-insensitive, lowercase first).

-- Run with args (`da` in LazyVim)
local function get_args(config)
  local args = type(config.args) == 'function' and (config.args() or {})
    or config.args
    or {}
  local args_str = type(args) == 'table' and table.concat(args, ' ') or args
  config = vim.deepcopy(config)
  config.args = function()
    local new_args = vim.fn.expand(vim.fn.input('Run with args: ', args_str)) --[[@as string]]
    if config.type == 'java' then
      return new_args
    end
    return require('dap.utils').splitstr(new_args)
  end
  return config
end

vim.keymap.set('n', '[DAP]a', function()
  require('dap').continue({ before = get_args })
end, { desc = 'DAP: run with args' })
vim.keymap.set('n', '[DAP]b', function()
  require('dap').toggle_breakpoint()
end, { desc = 'DAP: toggle breakpoint' })
vim.keymap.set('n', '[DAP]B', function()
  require('dap').set_breakpoint(vim.fn.input('Breakpoint condition: '))
end, { desc = 'DAP: breakpoint condition' })
vim.keymap.set('n', '[DAP]c', function()
  require('dap').continue()
end, { desc = 'DAP: run/continue' })
vim.keymap.set('n', '[DAP]C', function()
  require('dap').run_to_cursor()
end, { desc = 'DAP: run to cursor' })
vim.keymap.set('n', '[DAP]g', function()
  require('dap').goto_()
end, { desc = 'DAP: go to line (no execute)' })
vim.keymap.set('n', '[DAP]i', function()
  require('dap').step_into()
end, { desc = 'DAP: step into' })
vim.keymap.set('n', '[DAP]j', function()
  require('dap').down()
end, { desc = 'DAP: stack down' })
vim.keymap.set('n', '[DAP]k', function()
  require('dap').up()
end, { desc = 'DAP: stack up' })
vim.keymap.set('n', '[DAP]l', function()
  require('dap').run_last()
end, { desc = 'DAP: run last' })
vim.keymap.set('n', '[DAP]o', function()
  require('dap').step_out()
end, { desc = 'DAP: step out' })
vim.keymap.set('n', '[DAP]O', function()
  require('dap').step_over()
end, { desc = 'DAP: step over' })
vim.keymap.set('n', '[DAP]P', function()
  require('dap').pause()
end, { desc = 'DAP: pause' })
vim.keymap.set('n', '[DAP]q', function()
  require('dap').close()
end, { desc = 'DAP: close session' })
vim.keymap.set('n', '[DAP]r', function()
  require('dap').repl.toggle()
end, { desc = 'DAP: toggle REPL' })
vim.keymap.set('n', '[DAP]R', function()
  require('dap').restart()
end, { desc = 'DAP: restart session' })
vim.keymap.set('n', '[DAP]s', function()
  require('dap').session()
end, { desc = 'DAP: session' })
vim.keymap.set('n', '[DAP]t', function()
  require('dap').terminate()
end, { desc = 'DAP: terminate' })
vim.keymap.set('n', '[DAP]w', function()
  require('dap.ui.widgets').hover()
end, { desc = 'DAP: widgets hover' })
vim.keymap.set('n', '[DAP]x', function()
  require('dap').clear_breakpoints()
end, { desc = 'DAP: clear all breakpoints' })
