-- generated by rvpm hook converter; do not edit by hand

-- Denops fallback: if `deno` is not on PATH, use mise latest (§4.1).
if vim.fn.executable('deno') == 0 then
  local mise_deno = vim.fs.joinpath(
    vim.env.HOME,
    '.local/share/mise/installs/deno/latest/bin/deno'
  )
  if vim.fn.executable(mise_deno) == 1 then
    vim.g['denops#deno'] = mise_deno
  end
end

local deno_args_list = {
  '-q',
  '-A',
  '--unstable-kv', -- for Deno KV storage
  '--unstable-ffi', -- for deno-pty-ffi (https://github.com/sigmaSd/deno-pty-ffi)
}

vim.g.denops_server_addr = '127.0.0.1:32123' -- denops_shared_server_pueue

if vim.env.NVIM_DEBUG == 'true' then
  vim.g['denops#debug'] = true
  table.insert(deno_args_list, '--inspect')
end

-- denops.vim's default is ['-q', '--no-lock', '-A'];
vim.g['denops#server#deno_args'] = deno_args_list
