#!/usr/bin/env python3
"""Convert lua/hooks/*.dpp to rvpm per-plugin hook files. Re-runnable, deterministic."""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tomllib
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HOOKS_DIR = ROOT / "lua" / "hooks"
RVPM = ROOT / "rvpm"
DEPS = ROOT / "deps"
SHARED_LUA = ROOT / "lua" / "hooks" / "shared"

SECTION_RE = re.compile(
    r"^(?P<marker>--|\")\s*(?P<kind>lua_add|lua_source|hook_add|hook_source)\s+\{\{\{\s*$"
    r"(?P<body>.*?)"
    r"^(?P=marker)\s*\}\}\}\s*$",
    re.MULTILINE | re.DOTALL,
)
FT_BLOCK_RE = re.compile(
    r"^--\s*(?P<ft>[^\s]+)\s+\{\{\{\s*$"
    r"(?P<body>.*?)"
    r"^--\s*\}\}\}\s*$",
    re.MULTILINE | re.DOTALL,
)
HEREDOC_RE = re.compile(r"lua\s*<<\s*EOF\s*(?P<body>.*?)^EOF", re.MULTILINE | re.DOTALL)

DENOPS_AFTER = {
    "Shougo/ddu.vim": ("ddu", "ddu%.vim", "denops/ddu/app.ts"),
    "Shougo/ddc.vim": ("ddc", "ddc%.vim", "denops/ddc/app.ts"),
}

SHARED_CONSUMERS = {
    "ddc_skkeleton": ["Shougo/ddc.vim", "vim-skk/skkeleton"],
    "ddu_gin": ["Shougo/ddu.vim", "lambdalisue/vim-gin"],
}

GEN = "-- generated by rvpm hook converter; do not edit by hand\n"


def load_url_map() -> dict[str, str]:
    proc = subprocess.run(
        [sys.executable, str(ROOT / "doc/agents/scripts/dpp2rvpm.py")],
        capture_output=True,
        text=True,
        check=True,
    )
    report = json.loads(proc.stdout)
    out: dict[str, str] = {}
    for row in report["hooks_handoff"]:
        if row["url"] == "(global)":
            continue
        name = Path(row["dpp_hooks_file"]).name
        if "shared/" in row["dpp_hooks_file"]:
            continue
        out[name] = row["url"]
    out["tree-sitter-manager.nvim.dpp"] = "romus204/tree-sitter-manager.nvim"
    return out


def extract_lua(body: str) -> str:
    m = HEREDOC_RE.search(body)
    if m:
        return m.group("body").strip("\n")
    return body.strip("\n")


def parse_dpp(path: Path) -> list[tuple[str, str]]:
    text = path.read_text()
    sections: list[tuple[str, str]] = []
    for m in SECTION_RE.finditer(text):
        kind = m.group("kind")
        body = extract_lua(m.group("body"))
        if kind in ("hook_add", "lua_add"):
            target = "init.lua"
        else:
            target = "before.lua"
        sections.append((target, body))
    return sections


def parse_ft_dpp(path: Path) -> str:
    text = path.read_text()
    chunks: list[str] = [GEN, "-- from lua/hooks/ft.dpp (global filetype rules)\n"]
    for m in FT_BLOCK_RE.finditer(text):
        ft = m.group("ft")
        lua = extract_lua(m.group("body"))
        pattern = "*" if ft == "_" else ft
        chunks.append(
            f"vim.api.nvim_create_autocmd('FileType', {{\n"
            f"  pattern = {json.dumps(pattern)},\n"
            f"  callback = function()\n"
            + indent_lua(lua, 4)
            + "\n  end,\n})\n"
        )
    return "\n".join(chunks)


def indent_lua(lua: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in lua.splitlines())


def rvpm_dir(url: str) -> Path:
    return RVPM / "plugins" / "github.com" / url


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n")


def merge_parts(parts: list[str]) -> str:
    return GEN + "\n\n".join(p.strip() for p in parts if p.strip()) + "\n"


def shared_module(name: str, body: str, source: str) -> str:
    if not body.strip():
        body = f"-- {source}: empty hook body; see after/ftplugin/gin-log.lua for gin ddu integration"
    return (
        GEN
        + f"-- from {source}\n"
        + "local M = {}\n\n"
        + "function M.setup()\n"
        + indent_lua(body, 2)
        + "\nend\n\nreturn M\n"
    )


def denops_after_lua(name: str, rtp_pat: str, main_rel: str) -> str:
    return (
        GEN
        + f"-- P1/P4: register denops {name} (app.ts layout)\n"
        + "if vim.fn.exists('*denops#plugin#load') ~= 1 then\n"
        + "  return\n"
        + "end\n"
        + f'if vim.fn["denops#plugin#is_loaded"]("{name}") == 1 then\n'
        + "  return\n"
        + "end\n"
        + "for _, rtp in ipairs(vim.opt.rtp:get()) do\n"
        + f'  if rtp:match("/{rtp_pat}$") then\n'
        + f'    local main = rtp .. "/{main_rel}"\n'
        + "    if vim.fn.filereadable(main) == 1 then\n"
        + f'      pcall(vim.fn["denops#plugin#load"], "{name}", main)\n'
        + f'      pcall(vim.fn["denops#plugin#wait"], "{name}", {{ silent = 1 }})\n'
        + "    end\n"
        + "    break\n"
        + "  end\n"
        + "end\n"
    )


def inline_from_deps(
    url_map: dict[str, str], accounting: list[dict[str, str]]
) -> dict[str, dict[str, list[str]]]:
    """P3 inline hooks not in standalone .dpp files."""
    out: dict[str, dict[str, list[str]]] = defaultdict(lambda: defaultdict(list))
    dpp_urls = {
        url for name, url in url_map.items() if (HOOKS_DIR / name).exists()
    }

    def add(url: str, target: str, body: str, note: str) -> None:
        if url in dpp_urls:
            return
        out[url][target].append(f"-- inline from deps ({note})\n{body}")
        accounting.append(
            {
                "file": f"deps inline ({note})",
                "section": target.replace(".lua", ""),
                "dest": f"rvpm/plugins/github.com/{url}/{target}",
            }
        )

    for path in sorted(DEPS.glob("*.toml")):
        data = tomllib.loads(path.read_text())
        for plugin in data.get("plugins", []):
            url = plugin["repo"]
            if "hook_source" in plugin:
                vim = plugin["hook_source"].strip()
                lua = "\n".join(f'vim.cmd({json.dumps(line)})' for line in vim.splitlines() if line.strip())
                add(url, "before.lua", lua, "hook_source")
            if "lua_source" in plugin:
                add(url, "before.lua", plugin["lua_source"].strip(), "lua_source")
            if "lua_add" in plugin:
                add(url, "init.lua", plugin["lua_add"].strip(), "lua_add")
            if "ftplugin" in plugin:
                for ft, vim_body in plugin["ftplugin"].items():
                    lua = (
                        f"vim.api.nvim_create_autocmd('FileType', {{\n"
                        f"  pattern = {json.dumps(ft)},\n"
                        f"  callback = function()\n"
                        f"    vim.cmd([[{vim_body.strip()}]])\n"
                        f"  end,\n}})"
                    )
                    add(url, "before.lua", lua, f"ftplugin {ft}")
    return out


def main() -> int:
    url_map = load_url_map()
    buckets: dict[str, dict[str, list[str]]] = defaultdict(lambda: defaultdict(list))
    accounting: list[dict[str, str]] = []

    for dpp in sorted(HOOKS_DIR.rglob("*.dpp")):
        rel = dpp.relative_to(HOOKS_DIR)
        if rel.parts[0] == "shared":
            name = dpp.stem
            sections = parse_dpp(dpp)
            body = "\n\n".join(s for _, s in sections)
            mod_path = SHARED_LUA / f"{name}.lua"
            write_file(mod_path, shared_module(name, body, str(dpp.relative_to(ROOT))))
            for target, _ in sections:
                accounting.append(
                    {"file": str(dpp.relative_to(ROOT)), "section": target, "dest": str(mod_path.relative_to(ROOT))}
                )
            if not sections:
                accounting.append(
                    {"file": str(dpp.relative_to(ROOT)), "section": "(empty)", "dest": str(mod_path.relative_to(ROOT))}
                )
            continue

        if dpp.name == "ft.dpp":
            write_file(RVPM / "before.lua", parse_ft_dpp(dpp))
            accounting.append({"file": "lua/hooks/ft.dpp", "section": "ft blocks", "dest": "rvpm/before.lua"})
            continue

        url = url_map.get(dpp.name)
        if not url:
            print(f"WARN: no url mapping for {dpp.name}", file=sys.stderr)
            continue

        for target, body in parse_dpp(dpp):
            buckets[url][target].append(f"-- from lua/hooks/{dpp.name}\n{body}")
            accounting.append(
                {
                    "file": f"lua/hooks/{dpp.name}",
                    "section": target.replace(".lua", ""),
                    "dest": f"rvpm/plugins/github.com/{url}/{target}",
                }
            )

    for url, targets in inline_from_deps(url_map, accounting).items():
        for target, parts in targets.items():
            buckets[url][target].extend(parts)

    for shared, urls in SHARED_CONSUMERS.items():
        req = f'require("hooks.shared.{shared}").setup()'
        for url in urls:
            buckets[url]["before.lua"].append(f"-- shared multiple_hooks\n{req}")

    for url, targets in buckets.items():
        base = rvpm_dir(url)
        for target, parts in targets.items():
            write_file(base / target, merge_parts(parts))

    for url, (name, rtp, main) in DENOPS_AFTER.items():
        write_file(rvpm_dir(url) / "after.lua", denops_after_lua(name, rtp, main))

    report = {
        "sections_accounted": len(accounting),
        "accounting": accounting,
        "plugins_with_hooks": sorted(buckets.keys()),
        "denops_after": list(DENOPS_AFTER.keys()),
        "shared_modules": list(SHARED_CONSUMERS.keys()),
    }
    json.dump(report, sys.stdout, indent=2, ensure_ascii=False)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
