-- generated by rvpm hook converter; do not edit by hand
-- load denops file
vim.fn['ddt#custom#load_config'](
  vim.fn.expand('$NVIM_CONFIG_HOME/denops/ddt.ts')
)

-- MyGitStatus function (used in statusline)
local job = require('job')
local cached_status = {}

-- TODO: use plugin maybe.
function _G.MyGitStatus()
  local gitdir = vim.fn.finddir('.git', ';')
  if gitdir == '' then
    return ''
  end

  local full_gitdir = vim.fn.fnamemodify(gitdir, ':p')
  local gitdir_time = vim.fn.getftime(full_gitdir)
  local now = vim.fn.localtime()

  if
    not cached_status[full_gitdir]
    or gitdir_time > cached_status[full_gitdir].timestamp
    or now > cached_status[full_gitdir].check + 1
  then
    -- Get normal git status.
    -- The leading space separates the branch from the cwd that `userPrompt`
    -- (see `denops/ddt.ts`) prepends.
    local branch =
      vim.fn.trim(job.system({ 'git', 'rev-parse', '--abbrev-ref', 'HEAD' }))
    local status_lines = { ' ' .. branch }

    local git_status_output =
      job.system({ 'git', 'status', '--short', '--ignore-submodules=all' })
    for _, line in ipairs(vim.fn.split(git_status_output, '\n')) do
      if line ~= '' then
        table.insert(status_lines, '| ' .. line)
      end
    end

    local status = table.concat(status_lines, '\n')

    -- Detect unsaved buffers
    for _, buf in ipairs(vim.fn.getbufinfo({ buflisted = 1 })) do
      if buf.changed == 1 and buf.name ~= '' then
        status = status .. '\n'
        status = status
          .. ('| ?? ' .. vim.fn.fnamemodify(buf.name, ':.') .. ' (unsaved)')
      end
    end

    cached_status[full_gitdir] = {
      check = now,
      timestamp = gitdir_time,
      status = status,
    }
  end

  return cached_status[full_gitdir].status
end

-- Set terminal colors
vim.g.terminal_color_0 = '#6c6c6c'
vim.g.terminal_color_1 = '#ff6666'
vim.g.terminal_color_2 = '#66ff66'
vim.g.terminal_color_3 = '#ffd30a'
vim.g.terminal_color_4 = '#1e95fd'
vim.g.terminal_color_5 = '#ff13ff'
vim.g.terminal_color_6 = '#1bc8c8'
vim.g.terminal_color_7 = '#c0c0c0'
vim.g.terminal_color_8 = '#383838'
vim.g.terminal_color_9 = '#ff4444'
vim.g.terminal_color_10 = '#44ff44'
vim.g.terminal_color_11 = '#ffb30a'
vim.g.terminal_color_12 = '#6699ff'
vim.g.terminal_color_13 = '#f820ff'
vim.g.terminal_color_14 = '#4ae2e2'
vim.g.terminal_color_15 = '#ffffff'

-- Terminal mode keymaps (pum.vim integration)
vim.keymap.set('t', '<C-t>', '<Tab>', { desc = 'original <Tab>' })
-- NOTE: pum.vim actions must be deferred through <Cmd>, not called while the
-- <expr> mapping is being evaluated (textlock).
vim.keymap.set('t', '<Tab>', function()
  if vim.fn['pum#visible']() == 1 then
    return '<Cmd>call pum#map#select_relative(+1)<CR>'
  end
  return '<Tab>'
end, { expr = true, desc = '' })
vim.keymap.set('t', '<S-Tab>', function()
  if vim.fn['pum#visible']() == 1 then
    return '<Cmd>call pum#map#select_relative(-1)<CR>'
  end
  return '<S-Tab>'
end, { expr = true })
vim.keymap.set('t', '<Down>', function()
  vim.fn['pum#map#insert_relative'](1)
end)
vim.keymap.set('t', '<Up>', function()
  vim.fn['pum#map#insert_relative'](-1)
end)
vim.keymap.set('t', '<C-y>', function()
  if vim.fn['pum#visible']() == 1 then
    return '<Cmd>call pum#map#confirm()<CR>'
  end
  -- Terminal mode has no register paste, so prompt for the text instead.
  return '<Cmd>call feedkeys(""->input(), "n")<CR>'
end, { expr = true })
vim.keymap.set('t', '<C-o>', function()
  vim.fn['pum#map#confirm']()
end)
