-- generated by rvpm hook converter; do not edit by hand
-- Start ddt shell
vim.keymap.set('n', '[DP]s', function()
  vim.fn['ddt#start']({
    name = vim.t.ddt_ui_shell_last_name or ('shell-' .. vim.fn.win_getid()),
    ui = 'shell',
  })
end, { desc = 'ddt: shell' })
-- Start ddt terminal
vim.keymap.set('n', '[DP]t', function()
  vim.fn['ddt#start']({
    name = vim.t.ddt_ui_terminal_last_name
      or ('terminal-' .. vim.fn.win_getid()),
    ui = 'terminal',
  })
end, { desc = 'ddt: terminal' })

-- Ddu tab switcher
vim.keymap.set('n', '<C-t>', function()
  local split = vim.fn.has('nvim') == 1 and 'floating' or 'horizontal'
  vim.fn['ddu#start']({
    name = 'ddt',
    sync = true,
    uiParams = {
      ff = {
        split = split,
        winRow = 1,
        autoResize = true,
        cursorPos = vim.fn.tabpagenr(),
      },
    },
    sources = {
      { name = 'ddt_tab' },
    },
  })
end, { desc = 'ddt: tab switcher' })

-- Send selected text to current ddt UI
vim.keymap.set('x', '<Space>', function()
  vim.fn['ddt#ui#do_action']('send', {
    str = table.concat(
      vim.fn.getregion(
        vim.fn.getpos("'<"),
        vim.fn.getpos('.'),
        { type = vim.fn.mode() }
      ),
      '\n'
    ),
  }, vim.t.ddt_ui_name)
  vim.api.nvim_feedkeys(
    vim.api.nvim_replace_termcodes('<ESC>', true, false, true),
    'n',
    false
  )
end, { desc = 'ddt: send selection' })

-- Kill editor
vim.keymap.set('n', 'sD', function()
  vim.fn['ddt#ui#kill_editor']()
end, { desc = 'ddt: kill editor' })
