-- generated by rvpm hook converter; do not edit by hand
-- nvim-dap-ui setup (LazyVim style): auto open on session start, close on end.
-- nvim-dap is already sourced here (`depends` in deps/testing.toml).
local dap = require('dap')
local dapui = require('dapui')
dapui.setup({})
dap.listeners.after.event_initialized['dapui_config'] = function()
  dapui.open()
end
dap.listeners.before.event_terminated['dapui_config'] = function()
  dapui.close()
end
dap.listeners.before.event_exited['dapui_config'] = function()
  dapui.close()
end
