-- generated by rvpm hook converter; do not edit by hand
-- nvim-dap-ui keymaps. `require('dapui')` is called lazily inside callbacks;
-- `[DAP]` = `<Leader>D` (see mappings.lua), so `[DAP]u` == LazyVim `<leader>du`.
vim.keymap.set('n', '[DAP]u', function()
  require('dapui').toggle()
end, { desc = 'DAP: toggle DAP UI' })
vim.keymap.set({ 'n', 'x' }, '[DAP]e', function()
  require('dapui').eval()
end, { desc = 'DAP: eval' })
