-- generated by rvpm hook converter; do not edit by hand
vim.api.nvim_create_autocmd(
  { 'TabEnter', 'WinEnter', 'CursorHold', 'FocusGained' },
  {
    callback = function()
      vim.fn['ddu#ui#do_action']('checkItems')
    end,
  }
)
