-- generated by rvpm hook converter; do not edit by hand
-- inline from deps (lua_add)
vim.api.nvim_create_autocmd('LspAttach', {
  pattern = '*',
  group = vim.api.nvim_create_augroup('vimrc#augroup', { clear = false }),
  command = 'let b:ddu_source_lsp_clientName = "nvim-lsp"',
})
