# DO LIKE https://www.lazyvim.org/plugins/editor, but some plugins are
# delegated to `denops`; see other `deps` toml files.
# ---------------------------------------------------------------------------
# Integrations with some softwares
# ---------------------------------------------------------------------------

# gitsigns.nvim - Git integration for buffers
[[plugins]]
repo = "lewis6991/gitsigns.nvim"
on_event = ["BufReadPost", "BufNewFile"]
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/gitsigns.nvim.lua"

# TODO: merge it with other plugins via `multiple hooks`
# TODO: think that we can use `ddu` with this plugin;
#       or create new `ddu-ui` and `ddu-source` to show keymaps
# which-key.nvim - keybinding hints
[[plugins]]
repo = "folke/which-key.nvim"
on_event = "UIEnter"
hooks_file = "$NVIM_CONFIG_HOME/lua/hooks/which-key.nvim.lua"

