-- generated by rvpm hook converter; do not edit by hand
-- |lexima-customization|
local add_rule = vim.fn['lexima#add_rule']
add_rule({ char = '(', at = '\\%#\\w', input = '(' })

-- latex
add_rule({ char = '$', input_after = '$', filetype = 'latex' })
add_rule({ char = '$', at = '\\%#\\$', leave = 1, filetype = 'latex' })
add_rule({ char = '<BS>', at = '\\$\\%#\\$', delete = 1, filetype = 'latex' })
