-- generated by rvpm hook converter; do not edit by hand
-- Enable gin proxy editor so `git commit` can open the commit message in a
-- Neovim buffer via the denops proxy server (instead of failing due to
-- missing interactive terminal in the subprocess).
-- vim.g.gin_proxy_disable_editor = true

-- mappings (GIT)

-- Gin: patch
vim.keymap.set('n', '[GIT]ad', function()
  vim.cmd.GinPatch('++opener=tabnew', '%')
end, { desc = 'Gin: patch (tabnew)' })

-- TODO: ponder them
-- Add points ( `%`: current buffer, cancel is may `:cq`) by `--patch`
-- Add file by `--interactive`

-- Amend commit
vim.keymap.set('n', '[GIT]am', function()
  vim.cmd('Gin commit --amend')
end, { desc = 'Gin: amend commit' })

-- Branch;
vim.keymap.set('n', '[GIT]b', function()
  vim.cmd.GinBranch('++opener=tabnew')
end, { desc = 'Ddu: git branch' })

-- Commit (with editor via gin proxy): [GIT]c
-- Opens commit message in a Neovim buffer (requires gin proxy editor).
vim.keymap.set('n', '[GIT]c', function()
  vim.cmd('Gin commit -v')
end, { desc = 'Gin: commit (with editor)' })

-- Chaperon; solve git conflicts
vim.keymap.set('n', '[GIT]C', function()
  vim.cmd.GinChaperon('++opener=tabnew')
end, { desc = 'Gin: resolve conflicts' })

-- Diff
vim.keymap.set('n', '[GIT]d', function()
  vim.cmd.GinDiff('++opener=tabnew')
end, { desc = 'Gin: diff' })
-- Diff (Staged)
vim.keymap.set('n', '[GIT]D', function()
  vim.cmd.GinDiff('++opener=tabnew', '--cached')
end, { desc = 'Gin: diff (staged)' })

-- Edit
vim.keymap.set('n', '[GIT]e', function()
  -- TODO: use ddu as a source of suggestion
  local input = vim.split(
    vim.fn['cmdline#input']('GinEdit: ', '', 'path'),
    ',',
    { plain = true, trimempty = true }
  )
  if vim.tbl_isempty(input) then
    return
  end
  vim.cmd.GinEdit(input)
end, { desc = 'Gin: edit (path input)' })

-- Log (with graph): [GIT]l(or L)
vim.keymap.set('n', '[GIT]l', function()
  vim.cmd.GinLog(
    '--all',
    '--graph',
    '--max-count=100',
    '--oneline',
    '--decorate'
  )
end, { desc = 'Gin: log (all graph)' })

vim.keymap.set('n', '[GIT]p', function()
  vim.cmd('!git pull origin @')
end, { desc = 'Git: pull' })

-- Reflog: [GIT]r
vim.keymap.set('n', '[GIT]r', function()
  vim.cmd.GinReflog('++opener=tabnew')
end, { desc = 'Gin: Reflog' })

-- Gin status
vim.keymap.set('n', '[GIT]s', function()
  vim.cmd.GinStatus()
end, { desc = 'Gin: status' })

-- Git stash
vim.keymap.set('n', '[GIT]S', function()
  vim.cmd.GinStash()
end, { desc = 'Git: stash' })

-- Open browser; If visualmode, select current line's URL
vim.keymap.set({ 'n', 'x' }, '[GIT]o', function()
  vim.notify_once(
    'TODO: add browser or `xdg-open` to open URL',
    vim.log.levels.WARN
  )
  vim.cmd.GinBrowse()
end, { silent = true, desc = 'GIN: yank github url' })

-- Update: [GIT]u
vim.keymap.set('n', '[GIT]u', function()
  vim.cmd('silent !git add --update')
end, { silent = true, desc = 'git add --update' })

-- Yank; If visualmode, select current line's URL
vim.keymap.set({ 'n', 'x' }, '[GIT]y', function()
  vim.cmd.GinBrowse('++yank=+', '-n')
end, { silent = true, desc = 'GIN: yank github url' })
