-- generated by rvpm hook converter; do not edit by hand
-- Re-enable Treesitter with opt-out for specific filetypes/languages
-- and huge files. Treesitter is disabled by default in options.lua;
-- this runs when tree-sitter-manager.nvim is sourced.
-- NOTE: options.lua runs BEFORE this hook, so wrap the ORIGINAL start it
-- preserved (vimrc#treesitter_start_orig) — wrapping the no-op would keep
-- treesitter disabled forever.
-- https://github.com/neovim/neovim/pull/26347#issuecomment-1837508178
vim.treesitter.start = (function(wrapped)
  return function(bufnr, lang)
    local disables_ft = { 'help' }
    local disables_lang = { 'diff', 'latex' }

    local ft = vim.fn.getbufvar(bufnr or vim.fn.bufnr(''), '&filetype')
    if
      vim.tbl_contains(disables_ft, ft)
      or vim.tbl_contains(disables_lang, lang)
    then
      return
    end

    if bufnr then
      local max_filesize = 50 * 1024
      local ok, stats = pcall(vim.fs_stat, vim.api.nvim_buf_get_name(bufnr))
      if ok and stats and stats.size > max_filesize then
        return
      end
    end

    wrapped(bufnr, lang)
  end
end)(vim.g['vimrc#treesitter_start_orig'] or vim.treesitter.start)

-- Install parsers
require('tree-sitter-manager').setup({
  ensure_installed = {
    'go',
    'javascript',
    'lua',
    'luadoc', -- LuaDoc annotations inside lua comments (blog: prefer treesitter to LSP semantic tokens)
    'markdown',
    'markdown_inline',
    'python',
    'rust',
    'toml',
    'tsx',
    'typescript',
    'vim',
    'vimdoc',
  },
})

-- Treesitter highlighting fallback (kakehashi semantic tokens may be empty).
vim.api.nvim_create_autocmd({ 'FileType', 'BufRead' }, {
  pattern = {
    'go',
    'gomod',
    'gowork',
    'gotmpl',
    'javascript',
    'javascriptreact',
    'lua',
    'markdown',
    'markdown_inline',
    'python',
    'quarto',
    'rmd',
    'rust',
    'toml',
    'tsx',
    'typescript',
    'typescriptreact',
  },
  callback = function(args)
    vim.defer_fn(function()
      pcall(vim.treesitter.start, args.buf)
    end, 100)
  end,
})
