import type { DepsModel } from "./deps_as_json.ts";

function renderList(name: string, repos: string[]): string {
  if (repos.length === 0) return `M.${name} = {}`;
  const entries = repos.map((r) => `  '${r}',`).join("\n");
  return `M.${name} = {\n${entries}\n}`;
}

export function renderLua(model: DepsModel): string {
  const lines: string[] = [
    "-- AUTO-GENERATED by scripts/gen_deps.ts — do not edit by hand.",
    "-- Source: deps/{dpp,denops,neovim,merge}.toml",
    "-- Regenerate: `deno task gen`",
    "",
    "local M = {}",
    "",
    renderList("minimum_deps", model.minimum_deps),
    "",
    renderList("normal_deps", model.normal_deps),
    "",
    "return M",
  ];
  return lines.join("\n") + "\n";
}
