import type { DepsModel, PluginEntry } from "./deps_as_json.ts";
import { orderedSources, sourceLabel } from "./deps_as_json.ts";

function esc(s: string): string {
  return s.replace(/\|/g, "\\|");
}

function renderField(value: string[] | string | undefined): string {
  if (value === undefined) return "";
  if (typeof value === "string") return esc(value);
  return esc(value.join(", "));
}

function renderRtp(value: string | undefined): string {
  if (value === undefined) return "";
  return esc(`"${value}"`);
}

function renderDesc(p: PluginEntry): string {
  if (p.description === undefined || p.description === "") return "";
  return esc(p.description);
}

function hasHooks(p: PluginEntry): string {
  return p.has_hooks ? "✓" : "";
}

const HEADER = "| repo | description | if | on_ft | on_event | on_source | depends | external_commands | rtp | has_hooks |";
const SEPARATOR = "|------|-------------|----|-------|----------|----------|---------|-------------------|-----|-----------|";

function pluginRow(p: PluginEntry): string {
  const cells = [
    `\`${p.repo}\``,
    renderDesc(p),
    renderField(p.if_expr),
    renderField(p.on_ft),
    renderField(p.on_event),
    renderField(p.on_source),
    renderField(p.depends),
    renderField(p.external_commands),
    renderRtp(p.rtp),
    hasHooks(p),
  ];
  return `| ${cells.join(" | ")} |`;
}

export function renderReference(model: DepsModel): string {
  const lines: string[] = [
    "<!-- AUTO-GENERATED by scripts/gen_deps.ts — do not edit -->",
    "",
    "# Dependency list (auto-generated)",
    "",
    "Full per-plugin table across all `deps/**/*.toml`, grouped by source TOML.",
    "Regenerate via `deno task gen`; the pre-commit hook refuses stale output.",
    "",
  ];

  for (const source of orderedSources(model)) {
    const entries = model.by_toml.get(source) ?? [];
    if (entries.length === 0) continue;
    lines.push(`## ${sourceLabel(source)}`, "");
    lines.push(`${entries.length} plugin${entries.length === 1 ? "" : "s"}:`, "");
    lines.push(HEADER, SEPARATOR);
    for (const p of entries) {
      lines.push(pluginRow(p));
    }
    lines.push("");
  }

  lines.push(
    "---",
    "",
    "> Auto-generated by `scripts/gen_deps.ts` from `deps/**/*.toml`. Do not edit by hand. Regenerate via `deno task gen`; the pre-commit hook will refuse commits with stale output.",
    "",
  );

  return lines.join("\n");
}
