-- generated by rvpm hook converter; do not edit by hand
-- P1/P4: register denops ddc (app.ts layout)
if vim.fn.exists('*denops#plugin#load') ~= 1 then
  return
end
if vim.fn['denops#plugin#is_loaded']('ddc') == 1 then
  return
end
for _, rtp in ipairs(vim.opt.rtp:get()) do
  if rtp:match('/ddc%.vim$') then
    local main = rtp .. '/denops/ddc/app.ts'
    if vim.fn.filereadable(main) == 1 then
      pcall(vim.fn['denops#plugin#load'], 'ddc', main)
      pcall(vim.fn['denops#plugin#wait'], 'ddc', { silent = 1 })
    end
    break
  end
end
