-- generated by rvpm hook converter; do not edit by hand
-- rvpm merges denops only; shell_native needs bin/ on rtp for capture.zsh
do
  local name = 'ddc-source-shell_native'
  for _, rtp in ipairs(vim.opt.rtp:get()) do
    if rtp:match('/' .. name .. '$') then
      goto shell_native_rtp_done
    end
  end
  local repo = vim.fs.joinpath(
    vim.env.HOME,
    '.cache/rvpm/nvim/plugins/repos/github.com/Shougo',
    name
  )
  if vim.uv.fs_stat(repo) then
    vim.opt.rtp:append(repo)
  end
  ::shell_native_rtp_done::
end

vim.fn['ddc#custom#load_config'](
  vim.fn.expand(vim.fs.joinpath(vim.env.NVIM_CONFIG_HOME, 'denops', 'ddc.ts'))
)

-- kakehashi is the sole LSP client; ensure lsp source for markdown buffers.
for _, ft in ipairs({ 'markdown', 'markdown_inline' }) do
  vim.fn['ddc#custom#patch_filetype'](ft, {
    sources = { 'lsp', 'around', 'file', 'register', 'line' },
  })
end
-- KEYBINDS
-- Keys may sorted alphabetally.

-- FOR INSERT MODE COMPLETION
-- Config to use `pum.vim`; If you use `native-ui`, use `pumvisible`
vim.keymap.set('i', '<TAB>', function()
  if vim.fn['ddc#ui#inline#visible']() == 1 then
    vim.api.nvim_feedkeys(vim.fn['ddc#map#insert_item'](0), 'n', false)
    return ''
  elseif vim.fn['pum#visible']() == 1 then
    vim.fn['pum#map#insert_relative'](1, 'empty')
    return ''
  elseif vim.fn.col('.') <= 1 then
    return '<TAB>'
  elseif
    vim.fn
      .getline('.')
      :sub(vim.fn.col('.') - 1, vim.fn.col('.') - 1)
      :match('%s')
  then
    return '<TAB>'
  else
    return vim.fn['ddc#map#manual_complete']()
  end
end, { expr = true })
vim.keymap.set('i', '<S-Tab>', function()
  vim.fn['pum#map#insert_relative'](-1)
end, {})
vim.keymap.set('i', '<C-e>', function()
  if vim.fn['ddc#map#can_complete']() == 1 then
    vim.api.nvim_feedkeys(vim.fn['ddc#map#insert_item'](0), 'n', false)
    return ''
  else
    return '<End>'
  end
end, { expr = true })
vim.keymap.set('i', '<C-g>', function()
  return vim.fn['pum#map#toggle_preview']()
end, { desc = 'No `expr`' })
vim.keymap.set('i', '<C-g>', function()
  vim.api.nvim_feedkeys(vim.fn['ddc#map#insert_item'](0), 'n', false)
  return ''
end, { expr = true, desc = 'with `expr`' })
vim.keymap.set('i', '<C-l>', function()
  return vim.fn['ddc#map#manual_complete']()
end, { expr = true })
vim.keymap.set('i', '<C-n>', function()
  vim.fn['pum#map#select_relative'](1)
end)
vim.keymap.set('i', '<C-o>', function()
  vim.fn['pum#map#confirm_matched_pattern']('^\\S\\+')
end)
vim.keymap.set('i', '<C-p>', function()
  vim.fn['pum#map#select_relative'](-1)
end)
vim.keymap.set('i', '<C-t>', function()
  return '<C-v><Tab>'
end)
vim.keymap.set('i', '<C-y>', function()
  vim.fn['pum#map#confirm_suffix']()
end)

-- FOR COMMAND-LINE MODE COMPLETION
vim.keymap.set('c', '<Tab>', function()
  if vim.fn['ddc#ui#inline#visible']() == 1 then
    vim.api.nvim_feedkeys(vim.fn['ddc#map#insert_item'](0), 'n', false)
    return ''
  elseif vim.fn.wildmenumode() == 1 then
    return vim.fn.nr2char(vim.o.wildcharm)
  elseif vim.fn['pum#visible']() == 1 then
    return vim.fn['pum#map#insert_relative'](1)
  else
    return vim.fn['ddc#map#manual_complete']()
  end
end, { expr = true })
vim.keymap.set('c', '<S-Tab>', function()
  vim.fn['pum#map#insert_relative'](-1)
end)
vim.keymap.set('c', '<C-e>', function()
  if vim.fn['ddc#ui#inline#visible']() == 1 then
    vim.api.nvim_feedkeys(vim.fn['ddc#map#insert_item'](0), 'n', false)
    return ''
  elseif vim.fn['pum#visible']() == 1 then
    return vim.fn['pum#map#cancel']()
  else
    return '<End>'
  end
end, { expr = true })
vim.keymap.set('c', '<C-g>', function()
  vim.api.nvim_feedkeys(vim.fn['ddc#map#insert_item'](0), 'n', false)
  return ''
end, { expr = true })
vim.keymap.set('c', '<C-o>', function()
  vim.fn['pum#map#confirm']()
end)
vim.keymap.set('c', '<C-q>', function()
  vim.fn['pum#map#select_relative'](1)
end)
vim.keymap.set('c', '<C-y>', function()
  vim.fn['pum#map#confirm']()
end)
vim.keymap.set('c', '<C-z>', function()
  vim.fn['pum#map#select_relative'](-1)
end)

-- FOR TERMINAL MODE COMPLETION
-- Mouse Support
vim.keymap.set({ 'i', 'c', 't' }, '<LeftMouse>', function()
  vim.fn['pum#map#confirm_mouse']()
end, { desc = 'Left Mouse with pum.vim' })
vim.keymap.set({ 'i', 'c', 't' }, '<RightMouse>', function()
  vim.fn['pum#map#select_mouse']()
end, { desc = 'Right Mouse with pum.vim' })

-- Enable ddc (registers the denops plugin + autocmds).
-- Without this, patch_global() only stores config and no completion fires.
vim.fn['ddc#enable_terminal_completion']()
vim.fn['ddc#enable']({
  context_filetype = 'treesitter',
})

-- shared multiple_hooks
require('hooks.shared.ddc_skkeleton').setup()
