-- generated by rvpm hook converter; do not edit by hand
-- CommandLine settings for ddc
-- Functions for keymap
local function commandline_post()
  if vim.b.prev_buffer_config ~= nil then
    vim.fn['ddc#custom#set_buffer'](vim.b.prev_buffer_config)
    vim.b.prev_buffer_config = nil
  end
end

local function commandline_pre(mode)
  if vim.b.prev_buffer_config ~= nil then
    return
  end

  -- Overwrite sources
  vim.b.prev_buffer_config = vim.fn['ddc#custom#get_buffer']()

  if mode == ':' then
    vim.fn['ddc#custom#patch_buffer']('sourceOptions', {
      _ = {
        keywordPattern = '(~\\w+)?[0-9a-zA-Z_:#*/.-]*',
      },
    })

    -- Use zsh source for :! completion
    vim.fn['ddc#custom#set_context_buffer'](function()
      return vim.fn.stridx(vim.fn.getcmdline(), '!') == 0
          and {
            cmdlineSources = {
              'shell_native',
              'cmdline',
              'cmdline_history',
              'around',
            },
          }
        or {}
    end)
  end
  vim.api.nvim_create_autocmd('User', {
    pattern = 'DDCCmdlineLeave',
    group = vim.g['vimrc#augroup'],
    once = true,
    callback = commandline_post,
  })

  vim.fn['ddc#enable_cmdline_completion']()
end

-- KEYBINDS
-- --------------------------------------------------------------------------
-- n: {';;','?'}
-- x: {';;'}
-- --------------------------------------------------------------------------
--vim.keymap.set('n', ':', function()
--  commandline_pre(':')
--  vim.api.nvim_feedkeys(':', 'n', false)
--end, { desc = 'Cmdline with pre-processing' })
vim.keymap.set('n', '?', function()
  commandline_pre('/')
  vim.api.nvim_feedkeys('?', 'n', false)
end, { desc = 'Search with pre-processing' })
vim.keymap.set('n', ';;', function()
  vim.cmd('call cmdline#enable()')
  commandline_pre(':')
  vim.api.nvim_feedkeys(':', 'n', false)
end, { desc = 'Cmdline enable + pre-processing' })
vim.keymap.set('x', ';;', function()
  commandline_pre(':')
  vim.api.nvim_feedkeys(':', 'n', false)
end, { desc = 'Cmdline with pre-processing (visual)' })
