-- generated by rvpm hook converter; do not edit by hand
-- inline from deps (ftplugin qf)
vim.api.nvim_create_autocmd('FileType', {
  pattern = 'qf',
  callback = function()
    vim.cmd([[nnoremap <buffer> r <Cmd>Qfreplace<CR>]])
  end,
})
