-- generated by rvpm hook converter; do not edit by hand
vim.keymap.set('n', '[RUNNER]r', function()
  vim.cmd.OverseerToggle()
end, { desc = 'Task runner' })
vim.keymap.set('n', '[RUNNER]<Space>', function()
  vim.cmd.OverseerRun()
end, { desc = 'Task runner' })
