-- generated by rvpm hook converter; do not edit by hand
-- inline from deps (ftplugin help)
vim.api.nvim_create_autocmd('FileType', {
  pattern = 'help',
  callback = function()
    vim.cmd([[nnoremap <buffer> ,r  <Cmd>VimhelpLint!<CR>]])
  end,
})
