-- generated by rvpm hook converter; do not edit by hand
require('tokyonight').setup({
  transparent = true,
  styles = {
    sidebars = 'transparent',
    floats = 'transparent',
  },
})

vim.cmd([[colorscheme tokyonight-night]])

local colors =
  require('tokyonight.colors').setup(require('tokyonight.config').options)
vim.g['vimrc#colors'] = colors
vim.g['vimrc#color_bg'] = colors.bg

-- Refresh the palette when the colorscheme changes at runtime
vim.api.nvim_create_autocmd('ColorScheme', {
  callback = function()
    if vim.g.colors_name and vim.g.colors_name:match('tokyonight') then
      local colors =
        require('tokyonight.colors').setup(require('tokyonight.config').options)
      vim.g['vimrc#colors'] = colors
      vim.g['vimrc#color_bg'] = colors.bg
    end
  end,
})
